baseurl = "http://yingjiexue.com/"
relativeurls= true
languageCode = "en-us"
title = "Yingjie"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname="https-yjx-netlify-app-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$",  "_cache$"]
hasCJKLanguage= true
math = true
enableEmoji=true
footnotereturnlinkcontents= "↩"
rssLimit=100
[permalinks]
    en = "/:year/:month/:day/:slug/"
    cn = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "主页"
    url = "/"
    weight = 1
[[menu.main]]
    name = "日志"
    url = "/cn/"
    weight = 2      
  
[[menu.main]]
    name = "研究"
    url = "/research/"
    weight = 3  
    
[[menu.main]]
    name = "网站"
    url = "/Int_about/"
    weight = 4
[[menu.main]]
    name = "教学"
    url = "/teach/"
    weight = 5
    
[[menu.main]]
    name = "关于"
    url = "/cn_about/"
    weight = 6
    
[[menu.main]]
    name = "Blog"
    url = "/en/"
    weight = 7
[[menu.main]]
    name = "About"
    url = "/en_about/"
    weight = 8  
 
 
[params.utterances]
  enable = true
  repo = "yingjiexue/comments"
  issueTerm = "pathname"
  label = "blog-comments"
  theme = "github-ligh"

  
    
[params]
    description = ""
    footer="&copy; [Yingjie Xue](/)2020| [Github](https://github.com/yingjiexue)"
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    custom_head = ["head_custom.html"]


    MathJaxCDN = "https://mathjax.rstudio.com/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML"
    MathJaxVersion = "latest"
    

 

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Public"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


